# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class YodaTool < Formula
  desc ""
  homepage ""
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch-dan/yoda/releases/download/v1.0.5/yoda_1.0.5_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "26bc8939426abc226b061ba5cf365336ae6412734603c1d4586504448470f959"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch-dan/yoda/releases/download/v1.0.5/yoda_1.0.5_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "afbc9e65b5fd1b8566ad5518886b4e18bc8d8216c1bfac9b089e44597bdf4190"
    end
  end

  def install
    bin.install "yoda"
  end
end
