# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class YodaTool < Formula
  desc ""
  homepage ""
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch-dan/yoda/releases/download/v1.0.4/yoda_1.0.4_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5a7be8715ba64f13d5c16de87a938d81beccbeb283be3a473c9ed3abc772855d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch-dan/yoda/releases/download/v1.0.4/yoda_1.0.4_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e0725d9f8f5067ebbb6eb6e8791aeff76d7fa0f458a0d35cdbc3c9118122669e"
    end
  end

  def install
    bin.install "yoda"
  end
end
