# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class YodaTool < Formula
  desc ""
  homepage ""
  version "1.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch-dan/yoda/releases/download/v1.0.10/yoda_1.0.10_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "808de3dee08fe5e68b11ec39d44ec020b6d1930ce369edf3ac09fb0f5c49d611"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch-dan/yoda/releases/download/v1.0.10/yoda_1.0.10_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3f7c468866ceffee732d2a7c053966290df9aeb2f8a657cdc81a57e3b4bde2c1"
    end
  end

  def install
    bin.install "yoda"
  end

  def caveats; <<~EOS
    Requires multipass cask installed to function
  EOS
  end
end
